LazyStackDirectivesVersion: 1.1.0
Stacks:
  Dev:
    ProfileName: default
    RegionName: us-east-1
    StackName: PetStoreDev
    Stage: Dev
    UriCodeTarget: Debug/netcoreapp3.1
  Test:
    Stage: Test
    UriCodeTarget: Debug/netcoreapp3.1
    StackName: PetStoreTest
  Prod:
    Stage: Prod
    UriCodeTarget: Debug/netcoreapp3.1
    StackName: PetStore
ApiTagMap:
  HttpApiSecure:
  - order
  - pet
ProjectOptions:
  NugetPackageVersions:
    System.ComponentModel.Annotations: 5.0.0
    JsonSubTypes: 1.8.0
    Newtonsoft.Json: 13.0.1
    AWSSDK.Extensions.NETCore.Setup: 3.7.0.1
    Amazon.Lambda.AspNetCoreServer: 6.0.2
    Swashbuckle.AspNetCore: 6.1.4
    LazyStackAuth: 1.0.0
    System.IdentityModel.Tokens.Jwt: 6.11.1
  PetStoreClientSDK:
    Properties:
      DocumentationFile: bin\$(Configuration)\$(TargetFramework)\PetStoreClientSDK.xml
      RepositoryUrl: https://github.com/USER_ID/REPO_ID.git
      PackageReleaseNotes: Minor update
    PackageReferences:
      LazyStackAuth: ignore
    ProjectReferences:
    - ..\..\LazyStack\LazyStackAuth\LazyStackAuth.csproj
  Pet:
    ProjectReferences:
    - ..\..\Controllers\PetControllerImpl\PetControllerImpl.csproj
    ServiceRegistrations:
    - services.AddSingleton<PetStoreRepo.Models.IPetRepo, PetStoreRepo.Models.PetRepo>();
    - services.AddSingleton<PetStoreRepo.Models.ITagRepo,PetStoreRepo.Models.TagRepo>();
    - services.AddSingleton<PetStoreRepo.Models.ICategoryRepo,PetStoreRepo.Models.CategoryRepo>();
    - services.AddScoped<PetController.IPetController, PetControllerImpl.PetControllerImpl>();
  Order:
    ProjectReferences:
    - ..\..\Controllers\OrderControllerImpl\OrderControllerImpl.csproj
    - ..\..\Controllers\PetControllerImpl\PetControllerImpl.csproj
    ServiceRegistrations:
    - services.AddSingleton<PetStoreRepo.Models.IPetRepo, PetStoreRepo.Models.PetRepo>();
    - services.AddSingleton<PetStoreRepo.Models.IOrderRepo, PetStoreRepo.Models.OrderRepo>();
    - services.AddSingleton<PetStoreRepo.Models.ITagRepo,PetStoreRepo.Models.TagRepo>();
    - services.AddSingleton<PetStoreRepo.Models.ICategoryRepo,PetStoreRepo.Models.CategoryRepo>();
    - services.AddScoped<PetController.IPetController, PetControllerImpl.PetControllerImpl>();
  LambdaProjects:
    Runtime: dotnetcore3.1
    PackageReferences:
      AWSSDK.Extensions.NETCore.Setup: ''
      Amazon.Lambda.AspNetCoreServer: ''
    ServiceRegistrations:
    - services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
    - services.AddAWSService<Amazon.DynamoDBv2.IAmazonDynamoDB>();
    Properties:
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: LZDDB01
      Environment:
        Variables:
          TABLE_NAME:
            Ref: LZDDB01
          TABLE_ARN:
            Fn::GetAtt: LZDDB01.Arn
  WebApiProjects:
    PackageReferences:
      AWSSDK.Extensions.NETCore.Setup: ''
      Swashbuckle.AspNetCore: ''
    ServiceRegistrations:
    - services.AddSingleton<PetStoreRepo.Models.IPetRepo, PetStoreRepo.Models.PetRepo>();
    - services.AddSingleton<PetStoreRepo.Models.IOrderRepo, PetStoreRepo.Models.OrderRepo>();
    - services.AddSingleton<PetStoreRepo.Models.ITagRepo,PetStoreRepo.Models.TagRepo>();
    - services.AddSingleton<PetStoreRepo.Models.ICategoryRepo,PetStoreRepo.Models.CategoryRepo>();
    - services.AddScoped<PetController.IPetController, PetControllerImpl.PetControllerImpl>();
    - services.AddScoped<OrderController.IOrderController, OrderControllerImpl.OrderControllerImpl>();
    - services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
    - services.AddAWSService<Amazon.DynamoDBv2.IAmazonDynamoDB>();
    ProjectReferences:
    - ..\Controllers\OrderControllerImpl\OrderControllerImpl.csproj
    - ..\Controllers\PetControllerImpl\PetControllerImpl.csproj
  SchemaProjects:
    PackageReferences:
      Newtonsoft.Json: ''
  ClientSDKProjects:
    PackageReferences:
      LazyStackAuth: ''
      System.ComponentModel.Annotations: ''
      JsonSubTypes: ''
      Newtonsoft.Json: ''
  ControllerProjects:
    PackageReferences:
      System.IdentityModel.Tokens.Jwt: ''
AwsResources:
  LZDDB01:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: SK1
        AttributeType: S
      - AttributeName: SK2
        AttributeType: S
      - AttributeName: SK3
        AttributeType: S
      - AttributeName: SK4
        AttributeType: S
      - AttributeName: SK5
        AttributeType: S
      - AttributeName: GSI1PK
        AttributeType: S
      - AttributeName: GSI1SK
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: PK-SK1-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK1
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK2-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK2
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK3-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK3
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK4-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK4
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK5-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK5
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      GlobalSecondaryIndexes:
      - IndexName: GSI1
        KeySchema:
        - AttributeName: GSI1PK
          KeyType: HASH
        - AttributeName: GSI1SK
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName:
        Fn::Sub: ${AWS::StackName}-DB
